

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: family_erp_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - family_erp_network

  web:
    image: nginx:1.27
    container_name: family_erp_web
    restart: unless-stopped
    ports:
      - "8899:80"       # access app at http://localhost:8080
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - family_erp_network

  db:
    image: mysql:8.0
    container_name: family_erp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-family_erp}
      MYSQL_USER: ${MYSQL_USER:-family_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - family_erp_network

  queue:
    image: familyerp-app
    container_name: family_erp_queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - family_erp_network
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    env_file:
      - .env

  scheduler:
    image: familyerp-app
    container_name: family_erp_scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - family_erp_network
    command: >
      sh -c "while true; do
        php artisan schedule:run --verbose --no-interaction
        sleep 60
      done"
    depends_on:
      - db
      - app
    env_file:
      - .env

networks:
  family_erp_network:

volumes:
  db_data:
