[package]
name = "vasu2152004/family-erp-package"
version = "0.1.0"
description = "Laravel Family ERP"

[dependencies]
"php/php" = "8.3.4"

[fs]
# We map only the vital Laravel folders explicitly
"/app/public" = "public"
"/app/app" = "app"
"/app/config" = "config"
"/app/routes" = "routes"
"/app/resources" = "resources"
"/app/bootstrap" = "bootstrap"
"/app/database" = "database"
"/app/vendor" = "vendor"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
# This tells the server to look directly at the mapped public folder
main-args = ["-t", "/app/public", "-S", "localhost:8080"]