name: Deploy to Wasmer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Wasmer CLI
        run: curl https://get.wasmer.io -sSfL | sh

      - name: Add Wasmer to PATH
        run: |
          echo "$HOME/.wasmer/bin" >> $GITHUB_PATH
          echo "$HOME/.wasmer/globals/wasm/bin" >> $GITHUB_PATH

      - name: Login to Wasmer
        run: wasmer auth login ${{ secrets.WASMER_TOKEN }}
      
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader
        
      - name: Publish Package
        run: wasmer publish --no-confirm
        
        
      - name: Deploy App
        run: wasmer deploy --owner vasu2152004 --no-confirm
